sudo: false
notifications:
  email: false
language: python
python:
  - "3.5"
  - "3.6"
install:
  - pip install tox-travis
  - pip install coveralls
  - pip list
services:
  - mysql
before_script:
  - mysql -e 'create database mais;'
  - sh -c "mysql < tests/fixtures/tbl_games.sql"
  - sh -c "mysql < tests/fixtures/test_data.sql"
script:
  - tox
after_success:
  - coveralls
