sudo: false
notifications:
  email: false
language: python
matrix:
  fast_finish: true
  include:
    - python: '2.7'
    - python: '3.6'
    - python: '3.7'
      env: COVERAGE=1
  allow_failures:
    - python: '2.7'
    - python: '3.6'
install:
  - pip install tox-travis
  - pip install coveralls
  - pip list
services:
  - mysql
before_script:
  - mysql -e 'create database mais;'
  - sh -c "mysql < tests/fixtures/lkp_matchtypes.sql"
  - sh -c "mysql < tests/fixtures/tbl_games.sql"
  - sh -c "mysql < tests/fixtures/tbl_teams.sql"
  - sh -c "mysql < tests/fixtures/test_data.sql"
script:
  - tox
after_success:
  # For environments that ask for it, generate coverage
  - if [[ "$COVERAGE" == "1" ]]; then pip install -r requirements.txt; fi
  - if [[ "$COVERAGE" == "1" ]]; then coverage run --source mais -m py.test; fi
  - if [[ "$COVERAGE" == "1" ]]; then coverage report -m; fi
  - if [[ "$COVERAGE" == "1" ]]; then coveralls; fi
